<a href="https://colab.research.google.com/github/bhoop70233/einsum-operator/blob/main/einsum_operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**[Deep Learning with TensorFlow2]**
Einsum operator

In [1]:
import numpy as np

What is Einstein Summation Convention ?

Einstein summation is a convention for simplifying expression that includes summation of vectors, matrices or in general tensor. Remember scalar is zero rank tensor, vector is a rank one tensor and matrices are rank two tensors. Basically scalar, vectors and matrices are different forms of tensor based upon their rank.

In [2]:
import numpy as np
u = np.full((2,3),2)
print (u)

[[2 2 2]
 [2 2 2]]


In [3]:
print (np.einsum('ij->j',u))


[4 4 4]


In [4]:
print (np.einsum('ij->i',u))


[6 6]


In [6]:
x = np.full((2,3),2)
y = np.ones((3,4))
#Here there are two operands 'x' and 'y' and with dimension (2,3) and #(3,4)

#To write a einsum equation for this matrix - matrix multiplication
#what we need
print (np.einsum('ij,jk->ik',x,y))

[[6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [7]:
u = np.full((2,3),2)
v = np.ones((3,4))
#let's apply the rule #1
w = np.einsum('ij,jk -> ijk',u,v)
print (w.shape)
print (w)

(2, 3, 4)
[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [8]:
print (np.einsum('ijk -> ik',w))


[[6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [9]:
A = np.array([0, 1, 2])

B = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [12]:
(A[:, np.newaxis] * B).sum(axis=1)
array([ 0, 22, 76])

NameError: name 'array' is not defined

In [11]:
import numpy as np

In [13]:
import numpy as np

x = np.full((2,3),2)
y = np.ones((3,4))

# Print the result of matrix-matrix multiplication
print(np.einsum('ij,jk->ik', x, y))

# Apply rule #1 and print the shape and values of the resulting array
u = np.full((2,3),2)
v = np.ones((3,4))
w = np.einsum('ij,jk -> ijk', u, v)
print(w.shape)
print(w)

# Print the result of collapsing the array along the specified axis
print(np.einsum('ijk -> ik', w))

# Define arrays A and B
A = np.array([0, 1, 2])
B = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

# Calculate the desired result using broadcasting and sum
print((A[:, np.newaxis] * B).sum(axis=1))

[[6. 6. 6. 6.]
 [6. 6. 6. 6.]]
(2, 3, 4)
[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]]
[ 0 22 76]


In [14]:
# Step 1: Broadcasting
A_broadcasted = A[:, np.newaxis]
print(A_broadcasted)
# Output:
# array([[0],
#        [1],
#        [2]])

# Step 2: Element-wise Multiplication
product = A_broadcasted * B
print(product)
# Output:
# array([[ 0,  0,  0,  0],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

# Step 3: Summation
result = product.sum(axis=1)
print(result)
# Output:
# array([ 0, 22, 76])

[[0]
 [1]
 [2]]
[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]]
[ 0 22 76]


In [15]:
np.einsum('i,ij->i', A, B)
array([ 0, 22, 76])

NameError: name 'array' is not defined

In [16]:
import numpy as np

A = np.array([0, 1, 2])
B = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

# Calculate the desired result using einsum
result = np.einsum('i,ij->i', A, B)

# Print the result
print(result)

[ 0 22 76]


In [17]:
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [5, 5, 5]])

B = np.array([[0, 1, 0],
              [1, 1, 0],
              [1, 1, 1]])

In [18]:
 a = np.ones(300, dtype=np.int8)

In [19]:
np.sum(a) # correct result

300

In [20]:
np.einsum('i->', a) # produces incorrect result

44